### ISSUE TITLE
How to fix: No such file or directory: 'data\\corpora\\train-salsa-2.0.babelfied ?

### ISSUE THREAD

**Issue by chrisoutwright** [UKPLab/naacl18-multimodal-frame-identification#8]
II am trying to use the naacl18 but when running preprocess_data.py I encounter this issue:

```
2020-10-07 17:36:24,165 - INFO - Building dataset for [train-salsa-2.0] with imagined_embeddings [weights_imagined_vanilia_german_5mincount_IKRL.w2vt]
Traceback (most recent call last):
  File "H:/PycharmProjects/GPT_books/German_Facts_Extractor/Naacl/preprocess_data.py", line 151, in <module>
    generate_multimodal_dataset(resource_manager, CORPUS_SALSA2_DE.train, dict_embeddings)
  File "H:/PycharmProjects/GPT_books/German_Facts_Extractor/Naacl/preprocess_data.py", line 76, in generate_multimodal_dataset
    dataset.build()
  File "H:\PycharmProjects\GPT_books\German_Facts_Extractor\Naacl\basic_srl\dataset.py", line 286, in build
    sentences, annotations, babelfied_synset_annotations = read_corpus_with_babelfied_synset(sentence_file, annotation_file, babelfied_synset_annotation_file)
  File "H:\PycharmProjects\GPT_books\German_Facts_Extractor\Naacl\basic_srl\formats.py", line 102, in read_corpus_with_babelfied_synset
    with open(babelfied_synset_annotation_file, 'r') as nf:
FileNotFoundError: [Errno 2] No such file or directory: 'data\\corpora\\train-salsa-2.0.babelfied'
```

What is this babelfied file and why isn't it present? I've looked into the download_data.py and other src but I cannot demystify where it should be build.

**Comment by chrisoutwright** [comment]
Ok, I skipped the Hermann Dataset, that might be the reason. When training a model (the non multimodel one with Salsa) how can I use it as a Frame Extractor ?
